spring:
  application:
    name: cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 9411 #  Zipkin Server 的默认端口号

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false