spring:
  application:
    name: service-admin
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8673

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #配置注册中心地址